### ISSUE TITLE
taskset to the node where pmem device sits on 

### ISSUE THREAD

**Issue by zhouyuan** [Intel-bigdata/Spark-PMoF#17]
Instead of taskset to C0, we check the PMEM device and bind the thread to right node.
e.g. /dev/dax0.0 is on node0, then we taskset to some core on node 0.
 
https://github.com/Intel-bigdata/SSO/blob/a7ae44c3317d4e328169351ef628cc56c2d46578/src/main/scala/org/apache/spark/shuffle/pmof/PmemShuffleWriter.scala#L133

**Comment by tanghaodong25** [comment]
fixed. #57
