### ISSUE TITLE
Failed to open pmem pool

### ISSUE THREAD

**Issue by dcaceres88** [Intel-bigdata/Spark-PMoF#71]
Hello guys.

I am trying to run your project (**Release v1.0.2**) into a Spark standalone over Intel Optane persistent memory, but I have some problems with the deploy.I followed this guide (https://github.com/Intel-bigdata/Spark-PMoF/blob/master/doc/Spark-PMoF-enabling-guide.pdf) but I found some differences between the master branch:

- spark.shuffle.manager org.apache.spark.shuffle.pmof.RdmaShuffleManager ( I can´t found this class inside the project. 
I use spark.shuffle.manager org.apache.spark.shuffle.pmof.PmofShuffleManager instead  RdmaShuffleManager. 

But when run  databricks TPC benchmark I received this error:

```
Metastore DB connected: jdbc:sqlite:/tmp/spark-e2ba2c50-4d03-4bf1-aac5-430c740ef8ab/executor-c2b3dd32-9736-42e7-b7f5-71bf1b0820e7/spark_shuffle_meta.db
UPDATE devices SET mount_count = 4 WHERE device = '/dev/dax0.0'

Metastore DB: get unused device, should be /dev/dax0.0.
**failed to open pmem pool, errmsg: invalid major version (0)**
```

Previously, format my namespace as you said in your document:
Install and configure DCPM

1) Please install ipmctl and ndctl according to your OS version 2) Run ipmctl show -dimm to check whether dimms can be recognized 3) Run ipmctl create -goal PersistentMemoryType=AppDirect to create AD mode 4) Run ndctl list -R , you will see region0 and region1 in screen
5) Suppose we have 4x DCPM on two sockets. a) Run ndctl create-namespace –m devdax -r region0 -s 120g
e) T**hen we will see /dev/dax0.0**

My spark-defaults configuration is ( only for test pmem no RDMA):

```
spark.executor.extraClassPath      /opt/benchmarks_directory/Spark-PMoF/core/target/java-1.0-jar-with-dependencies.jar:/opt/benchmarks_directory/s
park-sql-perf/target/scala-2.11/spark-sql-perf_2.11-0.5.1-SNAPSHOT.jar
spark.driver.extraClassPath        /opt/benchmarks_directory/Spark-PMoF/core/target/java-1.0-jar-with-dependencies.jar:/opt/benchmarks_directory/s
park-sql-perf/target/scala-2.11/spark-sql-perf_2.11-0.5.1-SNAPSHOT.jar

spark.shuffle.manager org.apache.spark.shuffle.pmof.PmofShuffleManager

#new version
#spark.shuffle.manager org.apache.spark.shuffle.pmof.RdmaShuffleManager
spark.shuffle.pmof.enable_rdma false
spark.shuffle.pmof.enable_pmem true
spark.shuffle.pmof.max_stage_num 1
spark.shuffle.pmof.max_task_num 50000
spark.shuffle.spill.pmof.MemoryThreshold 16777216
spark.shuffle.pmof.pmem_capacity 100340914688
spark.shuffle.pmof.pmem_list /dev/dax0.0
spark.shuffle.pmof.dev_core_set dax0:0-71,dax0:0-71,dax1:0-71,dax1:0-71,dax0:0-71,dax0:0-71
spark.shuffle.pmof.server_buffer_nums 64
spark.shuffle.pmof.client_buffer_nums 64
spark.shuffle.pmof.map_serializer_buffer_size 262144
spark.shuffle.pmof.reduce_serializer_buffer_size 262144
spark.shuffle.pmof.chunk_size 262144
spark.shuffle.pmof.server_pool_size 3
spark.shuffle.pmof.client_pool_size 3
spark.shuffle.pmof.shuffle_block_size 2097152

```

My third party stack of libraries are ( I use this versions according with https://github.com/Intel-bigdata/Spark-PMoF/blob/master/docker/ubuntu18/DockerFile documentation):

- spark-2.3.0-bin-hadoop2.7
- pmdk 1.6
- libfabric v1.8.0
- HPNL spark-pmof-test branch

Can you help me?. And if you have one stack of libraries that you recommended, I would appreciate it.

**Comment by xuechendi** [comment]
Hi, Dcaceres

If you saw an error of “**failed to open pmem pool, errmsg: invalid major version (0)**”, it points to some underlying issue of persistent memory configuration, can you use pmempool info /dev/dax0.0 to check? And I suppose you have already installed pmdk, use pmdk unit test to check if pmem is working is also helpful.

And for org.apache.spark.shuffle.pmof.PmofShuffleManager instead RdmaShuffleManager, yes, you are right to that, we changed some package name, guide will be updated later.

I also CC @Eugene Ma<mailto:eugene.ma@intel.com> here, he is now helping other users doing hands on deployment, he may give you more advises.

Best regards,
Chendi

**Comment by dcaceres88** [comment]
Hi xuechendi
Thanks for your quick response. 
Today we were able to build with these commands:

```
ndctl create-namespace namespace -r region0 -s 120g --align=1G
mount -o dax /dev/pmem0.1 /mnt/pmemfs0.1
mkfs.ext4 /dev/pmem0.1
PMEMOBJ_CONF="sds.at_create=0" pmempool create --size 100G --layout pmemkv_layout obj /mnt/pmemfs/pool1.obj
```

Then, we relaunch Spark shell with TPC Benchmark, at the first moment Spark-Pmof now detect our pool correctly:

> Metastore DB connected: jdbc:sqlite:/tmp/spark-e2ba2c50-4d03-4bf1-aac5-430c740ef8ab/executor-f82f3f9e-61de-4df5-944a-a1ff4c7ae4c9/spark_shuffle_meta.db
> INSERT OR IGNORE INTO devices(device, mount_count) VALUES('/mnt/pmemfs0.1/pool1.obj', 1)
> 
> Metastore DB: get unused device, should be /mnt/pmemfs0.1/pool1.obj.
> List(bash, -c, cd /opt/benchmarks_directory/tpcds-kit/tools && ./dsdgen -table catalog_returns -filter Y -scale 1 -RNGSEED 100 )
> List(bash, -c, cd /opt/benchmarks_directory/tpcds-kit/tools && ./dsdgen -table inventory -filter Y -scale 1 -RNGSEED 100 )
> 

 But now receive other error in the middle of the process:

> Driver stacktrace:
>   at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1599)
>   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1587)
>   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1586)
>   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
>   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
>   at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1586)
>   at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
>   at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
>   at scala.Option.foreach(Option.scala:257)
>   at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:831)
>   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1820)
>   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1769)
>   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1758)
>   at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
>   at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
>   at org.apache.spark.SparkContext.runJob(SparkContext.scala:2027)
>   at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:194)
>   ... 83 more
> **Caused by: java.nio.BufferOverflowException**
>   at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:362)
>   at org.apache.spark.storage.pmof.PmemOutputStream.write(PmemOutputStream.scala:26)
>   at net.jpountz.lz4.LZ4BlockOutputStream.flushBufferedData(LZ4BlockOutputStream.java:220)
>   at net.jpountz.lz4.LZ4BlockOutputStream.write(LZ4BlockOutputStream.java:173)
>   at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
>   at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
>   at java.io.DataOutputStream.write(DataOutputStream.java:107)
>   at org.apache.spark.sql.catalyst.expressions.UnsafeRow.writeToStream(UnsafeRow.java:552)
>   at org.apache.spark.sql.execution.UnsafeRowSerializerInstance$$anon$1.writeValue(UnsafeRowSerializer.scala:69)
>   at org.apache.spark.storage.pmof.PmemBlockOutputStream.write(PmemBlockOutputStream.scala:62)
>   at org.apache.spark.shuffle.pmof.PmemShuffleWriter.write(PmemShuffleWriter.scala:94)
>   at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
>   at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
>   at org.apache.spark.scheduler.Task.run(Task.scala:109)
>   at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>   at java.lang.Thread.run(Thread.java:748)

Maybe we need some changes in our SparkPmof configurations inside the spark-defaults.conf file. Our file config is:

```
spark.shuffle.pmof.enable_rdma false
spark.shuffle.pmof.enable_pmem true
spark.shuffle.pmof.max_stage_num 1
spark.shuffle.pmof.max_task_num 5000
spark.shuffle.spill.pmof.MemoryThreshold 16777216
spark.shuffle.pmof.pmem_capacity 100340914688
spark.shuffle.pmof.pmem_list /mnt/pmemfs/pool1.obj,/mnt/pmemfs0.1/pool1.obj,/mnt/pmemfs0.5/pool1.obj,/mnt/pmemfs0.2/pool1.obj
spark.shuffle.pmof.dev_core_set dax0:0-71,dax0:0-71,dax1:0-71,dax1:0-71,dax0:0-71,dax0:0-71
spark.shuffle.pmof.server_buffer_nums 128
spark.shuffle.pmof.client_buffer_nums 16
spark.shuffle.pmof.map_serializer_buffer_size 502144
spark.shuffle.pmof.reduce_serializer_buffer_size 502144
spark.shuffle.pmof.chunk_size 262144
spark.shuffle.pmof.server_pool_size 3
spark.shuffle.pmof.client_pool_size 3
spark.shuffle.pmof.shuffle_block_size 2097152
#new conf
spark.shuffle.pmof.spill_throttle 8094304
```
We made different attempts changing client_buffer_nums, server_buffer_nums,map_serializer_buffer_size, reduce_serializer_buffer_size but the results was the same. 

Our spark-shell command is:

`./spark-shell --verbose --master spark://node5:7077 --conf spark.executor.cores=10 --conf spark.executor.memory=10g --conf spark.executor.memoryOverhead=1g --total-executor-cores 40 --conf "spark.executor.extraJavaOptions=-Dlog4j.configuration=file:/opt/benchmarks_directory/spark/spark-2.3.0-bin-hadoop2.7/bin/log4j.properties -Dvm.logging.name=myapp -Dvm.logging.level=DEBUG" --driver-java-options "-Dlog4j.configuration=file:/opt/benchmarks_directory/spark/spark-2.3.0-bin-hadoop2.7/bin/log4j.properties -Dvm.logging.level=DEBUG"`

Can you help us with this configuration?.

**Comment by xuechendi** [comment]
> PmemOutputStream.scala

Hi, @dcaceres88 

I noticed the error is caused by LZ4 codec, can you try change codec to snappy using below configuration
spark.io.compression.codec      snappy

LZ4 has some underlying error when using java ByteBufferOutputStream, so currently we only tested on snappy.
And another issue I should point out is that we normally test Spark-PMoF on devdax instead of fsdax, it should work fine with fsdax in "without RDMA" mode, but it will be best if you use devdax.

**Comment by maprietom** [comment]
Hi xuechendi

I am working together with @dcaceres88 in testing this project.

I tryed add snappy configuration that you indicated and the same error:
Generating table store_sales in database to hdfs://10.20.0.223:8020/user/tpcds_1G/store_sales with save mode Overwrite.
[Stage 6:=======================================================> (49 + 1) / 50]2020-05-20 11:14:46 WARN  TaskSetManager:66 - Lost task 0.0 in stage 6.0 (TID 750, 10.20.0.225, executor 1): java.nio.BufferOverflowException
	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:362)
	at org.apache.spark.storage.pmof.PmemOutputStream.write(PmemOutputStream.scala:26)
	at org.xerial.snappy.SnappyOutputStream.dumpOutput(SnappyOutputStream.java:360)
	at org.xerial.snappy.SnappyOutputStream.compressInput(SnappyOutputStream.java:374)
	at org.xerial.snappy.SnappyOutputStream.write(SnappyOutputStream.java:130)
	at org.apache.spark.io.SnappyOutputStreamWrapper.write(CompressionCodec.scala:207)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at org.apache.spark.sql.catalyst.expressions.UnsafeRow.writeToStream(UnsafeRow.java:552)
	at org.apache.spark.sql.execution.UnsafeRowSerializerInstance$$anon$1.writeValue(UnsafeRowSerializer.scala:69)
	at org.apache.spark.storage.pmof.PmemBlockOutputStream.write(PmemBlockOutputStream.scala:62)
	at org.apache.spark.shuffle.pmof.PmemShuffleWriter.write(PmemShuffleWriter.scala:94)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

We have also tried to use DEVDAX instead of FSDAX and we got this error:
Metastore DB connected: jdbc:sqlite:/tmp/spark-e2ba2c50-4d03-4bf1-aac5-430c740ef8ab/executor-c10b5331-a0e3-4ae3-8fbc-91372b3cc8ef/spark_shuffle_meta.db
INSERT OR IGNORE INTO devices(device, mount_count) VALUES('/dev/dax0.0', 1)

Metastore DB: get unused device, should be /dev/dax0.0.
failed to open pmem pool, errmsg: invalid major version (0)

Can you help us?

**Comment by JustD000** [comment]
Hi， Chendi Xue
I also encountered the same problem，can you help me？

**Comment by xuechendi** [comment]
> Hi， Chendi Xue
> I also encountered the same problem，can you help me？

Hi, @JustD000 
This issue is due some incorrect PMEM configuration, @Eugene-Mark , I know you have helped couple customer on this, can you add a quick debug and fixing under the Issue

**Comment by Eugene-Mark** [comment]
@maprietom As Chendi suggested, you'd better use devdax instead of fsdax. And as per the 'invalid marjor version(0)' you met, please make sure there is only one copy of PMDK available on your environment. Please track this [pmdk issues](https://github.com/pmem/pmdk/issues/4846) for the progress of this issue. For now, the most probable reason is that there are multiple versions of PMDK avaiable on your testing node.   

You can use 'find / -name "libpmemobj.so*"' to check whether there is only one version of PMDK. FYI, the libpmemobj is the main library from PMDK and used by Spark-PMoF project. 

You should expect some output like this: 
```
[root@clx-node1 application_1592134783911_0008]# find / -name "libpmemobj*"
/usr/lib64/libpmemobj.a
/usr/lib64/libpmemobj.so
/usr/lib64/libpmemobj.so.1
/usr/lib64/libpmemobj.so.1.0.0
/usr/local/include/libpmemobj.h
/usr/local/include/libpmemobj
/usr/local/lib64/pmdk_debug/libpmemobj.so.1.0.0
/usr/local/lib64/pmdk_debug/libpmemobj.a
/usr/local/lib64/pmdk_debug/libpmemobj.so.1
/usr/local/lib64/pmdk_debug/libpmemobj.so
/usr/local/lib64/libpmemobj.so.1.0.0
/usr/local/lib64/libpmemobj.a
/usr/local/lib64/libpmemobj.so.1
/usr/local/lib64/libpmemobj.so
/usr/local/lib64/pkgconfig/libpmemobj.pc
```

**Comment by Eugene-Mark** [comment]
@JustD000 Please check above comment.

**Comment by kelvin-qin** [comment]
For HDP Hadoop and spark，yum install libpmemobj++,It Works

**Comment by kelvin-qin** [comment]
@dcaceres88 The error message I encountered is the same as what you encountered, you can try the above method to see if it works.
